name: build

on:
  push:
    paths: [ '.github/scripts','.github/workflows/build.yml','py/**']
  pull_request:
    paths: [ '.github/scripts','.github/workflows/build.yml','py/**']

jobs:
  buildluna:
    uses: ./.github/workflows/buildluna.yml
  