name: build

on:
  push:
    paths: [ '.github/scripts/**','.github/workflows/**','py/**','cpp/**']
  pull_request:
    paths: [ '.github/scripts/**','.github/workflows/**','py/**','cpp/**']

jobs:
  buildluna:
    uses: ./.github/workflows/buildluna.yml
  